### ISSUE TITLE
Add Discord Logo and link to homepage

### ISSUE THREAD

**Issue by CaptainSplince** [akash-network/website-5-archive#110]
## Summary

Discord is our hub of community engagement. The website should add a logo and link to Discord next to the Twitter and Github logos.

### Basic example

A simple Discord logo and link to Discord in the top right corner of the website.

### Motivation

We need to drive new community members to our most engaging channels where they can actively get involved in community initiatives.

**Comment by brewsterdrinkwater** [comment]
this has been resolved
