### ISSUE TITLE
Token Page (facelift & adding illustrations)

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website-5-archive#147]
## Summary

Brief explanation of the feature.

- By adding illustrations we will achieve visual interest and variety for this page. 
- Increasing whitespace between section, adding style and hierarchy to typography will create a sense of balance and well executed design. 

### Basic example

![akash-akt-token](https://user-images.githubusercontent.com/116030971/233367399-672ace2b-0bf2-4d71-9f41-725ea9627698.png)

### Assets

![Incentivization](https://user-images.githubusercontent.com/116030971/233367463-87d362cf-8424-4ff3-aea1-4f6670ba9d58.svg)
![value-exchange](https://user-images.githubusercontent.com/116030971/233367466-32d21e0a-247b-4749-b9f9-01591cd836df.svg)
![governance](https://user-images.githubusercontent.com/116030971/233367469-803a10e3-d0b7-41cd-987f-f7be65a0931b.svg)
![security](https://user-images.githubusercontent.com/116030971/233367473-4d265980-73f7-4d30-a95b-e821a1376d0a.svg)
![akt-token](https://user-images.githubusercontent.com/116030971/233367477-0d6263d6-b110-49d3-9547-ffeace9bf092.svg)

**Comment by ArthurEmma2** [comment]
working on this page

**Comment by brewsterdrinkwater** [comment]
This page was completed and taken live by @ArthurEmma2 

https://github.com/akash-network/website/pull/187
