### ISSUE TITLE
wg-akash-website: Updates for gpu-testnet page

### ISSUE THREAD

**Issue by brewsterdrinkwater** [akash-network/website-5-archive#165]
These are changes to the Akash.network/gpu-testnet page.

- [ ] Change the dates for the GPU Testnet to "June 20th, 2023 - July 11th, 2023"
<img width="1555" alt="Screen Shot 2023-06-08 at 2 14 23 PM" src="https://github.com/akash-network/website/assets/9482916/7874aee8-4612-4f19-b787-9a98a7de9bde">

- [ ] Add link for "GPU Docs" to (https://docs.akash.network/other-resources/experimental/testnet)
- [ ] Remove button for "KYC Guidelines"

**Comment by anilmurty** [comment]
Also update Tensorflow to Pytorch (Torchbench) (ref: https://github.com/akash-network/community/pull/242)

**Comment by zachhorn** [comment]
Additional changes:


<img width="500" alt="Screen Shot 2023-06-08 at 4 11 05 PM" src="https://github.com/akash-network/website/assets/24351900/05d8c2ce-5ec6-4646-8eba-6a059030af83">

- Remove the periods at the end of "Set up a GPU provider" and "Deploy AI models"
- Change the copy to "Benchmark GPUs using PyTorch"

--

<img width="500" alt="Screen Shot 2023-06-08 at 4 18 48 PM" src="https://github.com/akash-network/website/assets/24351900/dfba022e-7a2b-4b32-b3b8-db4a5389db64">

- Remove the highlighted copy
- Remove the section divider above the highlighted copy

--

<img width="500" alt="Screen Shot 2023-06-08 at 4 20 15 PM" src="https://github.com/akash-network/website/assets/24351900/75c83e25-745c-4cf4-900a-8c3dcbb3d9fb">

- Change the highlighted copy to "Be among the first to test a revolutionary open-source marketplace for GPU compute"

**Comment by brewsterdrinkwater** [comment]
PR #166 solves this issue from @ArthurEmma2
