### ISSUE TITLE
Community Page Font is Dark

### ISSUE THREAD

**Issue by CaptainSplince** [akash-network/website-5-archive#168]
## Description

The community page font is dark and I can not see it in dark mode.
[See Here](https://ibb.co/28gqJmp)

### Steps to reproduce

Go to to https://akash.network/community/ to see the font.

### Expected result

Should be able to read the font in dark mode when you go to the website

### Actual result

The font is too dark to read

**Comment by okhaimie-dev** [comment]
I believe this issue can be closed now = it seems to have been resolved

**Comment by brewsterdrinkwater** [comment]
This issue was solved by https://github.com/akash-network/website/pull/170
