### ISSUE TITLE
Update Docs Link in GPU Testnet Page.

### ISSUE THREAD

**Issue by brewsterdrinkwater** [akash-network/website-5-archive#169]
The docs link has changed, as docs are out of experimental. 

Can you update the Docs link to https://docs.akash.network/testnet

<img width="1571" alt="Screen Shot 2023-06-13 at 12 26 58 PM" src="https://github.com/akash-network/website/assets/9482916/64ba61ff-d8c3-4a2a-853b-41ba4e6f3491">

**Comment by okhaimie-dev** [comment]
This issue should also be closed now, as it has been fixed.

You can verify at:
https://akash.network/gpu-testnet/
