### ISSUE TITLE
Newsletter submission text field not functional

### ISSUE THREAD

**Issue by zachhorn** [akash-network/website-5-archive#182]
The newsletter submission text field on the homepage of akash.network isn't able to accept text entry. It appears the Subscribe button links directly to the newsletter signup Typeform.

I would recommend removing the text field and including a button to "Subscribe"

<img width="1182" alt="Screen Shot 2023-06-27 at 7 41 32 AM" src="https://github.com/akash-network/website/assets/24351900/85158741-4616-4669-878a-66f2d0667cc8">

**Comment by aktdenis** [comment]
@zachhorn could you provide a link to set-up the newsletter, ty!
@ArthurEmma2 any chance you have a look at this issue? also note, that the icon should be an svg - now it looks low-res. (please have a look at the figma drawing)

**Comment by ArthurEmma2** [comment]
@aktdenis have already removed the text field. It’s only left with the subscribe button. For we to set up the text field to accept emails from users we need an API.

**Comment by zachhorn** [comment]
Here's the link to the newsletter signup: https://akashnet.typeform.com/to/awKX5bPw

@ArthurEmma2 Would you post an image of what the subscribe button looks like currently?

**Comment by ArthurEmma2** [comment]
![Web capture_29-6-2023_215238_localhost](https://github.com/akash-network/website/assets/86601468/1ade827c-37f3-452a-8653-871dc6c40bf1)

**Comment by aktdenis** [comment]
@brewsterdrinkwater issue solved
