### ISSUE TITLE
Improve blog post image resolution

### ISSUE THREAD

**Issue by zachhorn** [akash-network/website-5-archive#184]
**Request for improvement:** Experiment with ways to increase the display resolution of blog post header images without compromising site speed. Are we able to display images in high quality without creating significantly longer page load times.

<img width="1205" alt="Screen Shot 2023-06-27 at 7 47 12 AM" src="https://github.com/akash-network/website/assets/24351900/b93e6f19-7002-4f19-9d17-15d74f95f93b">

**Comment by ArthurEmma2** [comment]
@zachhorn this issue has been solved can you please close it.

**Comment by aktdenis** [comment]
@brewsterdrinkwater this issue has been solved
