### ISSUE TITLE
Issues with blog preview section cards

### ISSUE THREAD

**Issue by zachhorn** [akash-network/website-5-archive#185]
A few issues with the section of the homepage that previews the most recent blog posts:

1. The bottom part of the cards for each individual post expands on hover and is clickable, but the graphic directly above is disconnected from the hover and is not clickable.
2. Images are not displaying in the correct aspect ratio. (In the image below, the blog graphics in the middle and on the right are compressed).
3. The author and the blog category (above the post title) should be clickable (independent of the blog post itself). I.e. the user should be able to click "Greg Osuri" on the preview card and be taken to his author page.

<img width="1332" alt="Screen Shot 2023-06-27 at 7 49 31 AM" src="https://github.com/akash-network/website/assets/24351900/1b21d2a6-f8cb-431b-a167-c10218023ed9">

**Comment by aktdenis** [comment]
@brewsterdrinkwater issue solved
