### ISSUE TITLE
Responsive homepage section, improvements to scroll behavior 

### ISSUE THREAD

**Issue by zachhorn** [akash-network/website-5-archive#186]
The scrolling behavior in the section below would ideally show each of the three sections on the left highlighted (or emphasized) as the user scrolls down the page.

It would also be helpful to indicate clear correspondences between items on the right list and their related sections on the left list.

<img width="1362" alt="Screen Shot 2023-06-27 at 7 54 32 AM" src="https://github.com/akash-network/website/assets/24351900/84198fb9-fa52-484d-873a-4e2df38be5ee">

**Comment by ArthurEmma2** [comment]
Hey, @zachhorn the items on the left are clickable a click on each item will scroll down to the appropriate item on the right list. 

https://github.com/akash-network/website/assets/86601468/c02fa879-d92c-4352-b0a5-6ec5853a7e03

**Comment by aktdenis** [comment]
@ArthurEmma2 as you see in the image attached, none of the menu items is highlighted. When the user reaches the first group the first menu item should be highlighted (infrastructure and resource management). The same goes when the users scrolls to second and third group. <img width="1619" alt="Screenshot 2023-07-05 at 09 52 16" src="https://github.com/akash-network/website/assets/116030971/ac8915f8-7e44-4682-8e6d-7ac5cf1667aa">

**Comment by aktdenis** [comment]
This image might provide better explanation. When the user scroll to a specific group of items, the menu on the right should indicate that. <img width="1899" alt="Screenshot 2023-07-05 at 09 56 17" src="https://github.com/akash-network/website/assets/116030971/f9a799db-253e-4a20-9c4b-8872da915733">

**Comment by ArthurEmma2** [comment]
Thanks @aktdenis got it 👍
