### ISSUE TITLE
Blog Page redesign

### ISSUE THREAD

**Issue by ArthurEmma2** [akash-network/website-5-archive#192]
The Blog Page Redesign project aims to improve the website's blog section's user experience and visual appeal. it has become evident that the current design requires a refresh to better showcase the articles and facilitate easy navigation. This redesign initiative focuses on optimizing the layout, implementing responsive design for seamless mobile access, and incorporating intuitive features to encourage user interaction. By revamping the blog page, we anticipate higher user retention, increased readership, and a more delightful experience for our audience.

Time needed to complete: 20 hours
Hourly Rate: $30/hour

**Comment by aktdenis** [comment]
Hey Arthur, 

Thanks for the initiative! We have a couple of other pending issues we should tackle first. Since the issue is mostly UI/UX related we might need to add visualisations for better understanding and execution.

**Comment by aktdenis** [comment]
Providing a design draft for Blog:
<img width="835" alt="Screenshot 2023-08-10 at 16 20 47" src="https://github.com/akash-network/website/assets/116030971/27f6a886-2136-4a1b-9d5c-588dfbf340f0">

A detail page for Blog post:
<img width="738" alt="Screenshot 2023-08-10 at 16 24 07" src="https://github.com/akash-network/website/assets/116030971/63e80938-cc8c-41ec-949f-516443d2dba8">

Up for feedback, discussion.  @brewsterdrinkwater @brewsterdrinkwater @hoomanhq @zachhorn
