### ISSUE TITLE
Create a Footer 

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website-5-archive#194]
## Summary

We need a footer on Akash website to avoid a dead-end. 

### Basic example
<img width="1295" alt="Screenshot 2023-07-11 at 12 53 26" src="https://github.com/akash-network/website/assets/116030971/2c5b95d7-70e1-4337-955c-db7148905456">

### Motivation

We'd like to give user a possibility to continue browsing.

**Comment by ArthurEmma2** [comment]
awesome

**Comment by aktdenis** [comment]
Based on the feedback and the conversations, adding a new design:
<img width="1270" alt="Screenshot 2023-08-10 at 16 49 20" src="https://github.com/akash-network/website/assets/116030971/ab356757-c278-4bd0-8da2-93d8f88dec57">
