### ISSUE TITLE
GPU Demand Landing Page

### ISSUE THREAD

**Issue by brewsterdrinkwater** [akash-network/website-5-archive#200]
## Summary

New Akash GPU Demand Landing Page that visitors can see organically or via marketing campaigns, that provides a questionaire on demand needs on the Akash Network for GPUs. **There is a bounty for this page.**

### Due Date

ASAP (Latest July 31st, 2023)

### Motivation

Akash wants to have a landing page that serves as an intake form, which asks basic qualifying questions to build an internal database of potential demand-side customers on the Akash Network. 

### Next Steps

- [ ] Mockup Design from Denis | Core Team
- [ ] Typeform created to ask visitors appropriate questions on Demand. Answers will be tracked in a spreadsheet.
- [ ] Share Typeform embed link with page developer
- [ ] Development of New GPU Demand Landing page on the Akash Network Website.

**Comment by aktdenis** [comment]
any content ready for this page? what can we bring from the GPU Tesnet page? cc @zachhorn

**Comment by ArthurEmma2** [comment]
@aktdenis  Let me know when the design is done
