### ISSUE TITLE
Update Menubar

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website-5-archive#201]
## Summary

An issue brought up in the last WG-Akash-Website meeting from Zach and Hewie. 
We are currently missing a prominent button to launch Console. Along with that adding a diagonal arrow would help users understand that the action is going to be performed in a new tab. 

### Basic example
<img width="2048" alt="Screenshot 2023-07-26 at 15 01 52" src="https://github.com/akash-network/website/assets/116030971/abc69601-1785-4439-b407-4e4f2901bd53">

### Motivation

- Adding an arrow next to a clickable item will indicate that the action will open a new tab.
- Adding a button "Launch Console" will bring more users to the deployment tool.

**Comment by aktdenis** [comment]
cc @zachhorn

**Comment by ArthurEmma2** [comment]
https://github.com/akash-network/website/assets/86601468/34f95e96-7340-461b-afdf-9940ebf66d06


@aktdenis

**Comment by aktdenis** [comment]
hey @zachhorn, what are your thoughts? Imo, might be a little too crowded on the right side of the bar

**Comment by zachhorn** [comment]
It's a bit crowded, but I do like the launch button up there in the nav.

The alignment on the arrow in the Launch Console button catches my eye as well.
