### ISSUE TITLE
CTA: Get Started (adding additional options)

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website-5-archive#215]
## Summary

At the moment “Get Started” directs users to use “Akash Console”

Possibilities with Akash extends beyond this single option. Listed below, couple of options;

- Deploy (Console, Cloudmos, CLI…)
- Become a provider (Praetor)
- Documentation (Dive deep and learn)
- Join the community (join insiders, validators, propose an idea)

### Basic example

Problem:
Lack of awareness for users to choose between different options, which might align with their needs...

### Motivation

Solution:
We guide users through a decision tree to choose one of the options. We offer dedicated pages for offered products. Each path leads users where they can find detailed information. 

Sitemap:
<img width="930" alt="Screenshot 2023-08-10 at 13 58 26" src="https://github.com/akash-network/website/assets/116030971/e5913a98-12a6-43c8-a7b3-0b3371723182">

**Comment by mnlytic** [comment]
This is nice!

Any direction for people that wanna build on Akash?

**Comment by ArthurEmma2** [comment]
Great Move

**Comment by aktdenis** [comment]
Providing additional information and a draft below. 
When a user clicks "Get Started", is presented with several options. Main are:
- deploy
- join providers
- view documentation
On a secondary level we present CTAs to join Insiders, Validators or propose an idea.
<img width="1200" alt="Screenshot 2023-08-10 at 15 08 22" src="https://github.com/akash-network/website/assets/116030971/4297edfd-17cb-409c-abb1-9ea59ec31b3f">

Screen for deployment tools is offering two options; Console and Cloudmos. Each have a place for a short description, different possibilites with CTAs (Launch, Docs, Product Tour - optional). Optional - in the second row we could display additional resources such as tutorials, channels, guides etc. 

On a third level we offer additional options for deployments (Terraform, CLI, Client Libraries,...)

Same dedicated product layout is offered for Cloudmos, Praetor
<img width="1016" alt="Screenshot 2023-08-10 at 15 10 26" src="https://github.com/akash-network/website/assets/116030971/252a2698-ef50-4a2f-b535-e5dfd2379d8b">

**Comment by HoomanHQ** [comment]
This seems really great plan..

**Comment by aktdenis** [comment]
> This is nice!
> 
> Any direction for people that wanna build on Akash?

you mean building an app-chain or design contribution? :) 

@ArthurEmma2 @HoomanHQ 🙏🏼

**Comment by ArthurEmma2** [comment]
if this is the final design i will surely start the implementation

**Comment by aktdenis** [comment]
@ArthurEmma2 let's wait for community and team feedback.
