### ISSUE TITLE
Homepage Re-Design & Content Revamp

### ISSUE THREAD

**Issue by aktdenis** [akash-network/website-5-archive#216]
## Summary

Creating this issue based on community members feedback:

**_1. Hero Section:_**

Community feedback:
- Not really sure what "Sovereign infrastructure that scale" means
- Can we incorporate Supercloud to the headline
- Headline is not descriptive enough to explain what Akash does
- Get started is not fairly serving other projects and options (Cloudmos, Praetor, etc.) - covered in issue https://github.com/akash-network/website/issues/215

Things to consider for hero headline;
_* When asked how would you describe Akash these were the answers:_
- Cloud computing - unleashed
- Elevate your cloud game
- Decentralized Cloud Compute
- People’s cloud
- Decentralized Supercloud
- Your cloud, your way
- Your cloud, your business
- Akash Supercloud; Gateway to computing resources 
- Own your Cloud
- Supercloud computing, on your terms
- Akash Supercloud. Use when you need it, earn when you don’t.
-  Akash SuperCloud. The free market for computing power
Most projects struggle with high cost and low availability of computing power.
Akash closes the gap between buyers and sellers of server and GPU resources so projects can focus on building their projects.

**_2. 9 paragraphs_**
Although we made some changes to the previous layout there are requests to improve this section:

- _"There is a lot of smaller paragraphs at the end of the page. That part could be more engaging if either shorter or divided to different sections, layout,... make it more appealing."_
- _"Could be more fun, bit boring."

**_3. Community_**
- "Could we emphasize community, adding a CTA to join discord, discussions"

**_4. Additional requests_**
* Can we add a section which says “what others say…” (we can pull relevant tweets)
* What’s possible with Akash - a quick glance at tools, templates (direct links to awesome akash repo, console, cloudmos, preaetor app)

**Comment by aktdenis** [comment]
Providing a design draft, based on the information above:

Headline is up for discussion. UVP is served right away after a first scroll. Bulletpoints (supported with different icons) could be shorter. 
<img width="1230" alt="Screenshot 2023-08-10 at 17 00 29" src="https://github.com/akash-network/website/assets/116030971/ffaa08f2-ce4c-4917-b314-793befe36843">

To reduce the amount of smaller pharagraphs (went from 9 to 6) we can add that information to this section. (Still keeping the previous content, just served differently)

<img width="1255" alt="Screenshot 2023-08-10 at 17 02 30" src="https://github.com/akash-network/website/assets/116030971/69668b36-a369-497a-94f3-a87d9b9f92eb">

A suggestion to create a section where we showcase the possibilty of Akash has a valid point:
<img width="1254" alt="Screenshot 2023-08-10 at 17 04 07" src="https://github.com/akash-network/website/assets/116030971/ade0ceec-83e7-4e7f-9f1c-91e42d20855f">

Previous section "Built for battle, commanded by the community" can include "what others say..." (pulling relevant tweets)
<img width="1409" alt="Screenshot 2023-08-10 at 17 05 06" src="https://github.com/akash-network/website/assets/116030971/18d89048-885c-4cf2-a265-2270717de1c8">

And the whole page:
![akash-homepage](https://github.com/akash-network/website/assets/116030971/c44f723d-64bd-4de7-ae83-4e02f113739d)

**Comment by HoomanHQ** [comment]
@aktdenis suggestion for hero title:

"Unleash the Power of Akash Supercloud: Your Cloud, Your Way"

**Comment by mnlytic** [comment]
https://github.com/akash-network/website/assets/12068740/8b233b1f-2a90-4bbf-bcb9-1e04734fd5c9

@aktdenis @brewsterdrinkwater  Ideas for the website copy.

**Top Headline:** 
Akash SuperCloud

**Main Headline:** 
The free market for computing power

**Oneliner:** 
Most projects struggle with high cost and low availability of computing power.
Akash closes the gap between buyers and sellers of server and GPU ressources so projects can focus on building their projects.


Link to the Figma
https://www.figma.com/file/CMultwTtRESAvNSZLBZHth/Akash-Website-Copy-Ideas?type=design&node-id=0%3A1&mode=design&t=G28PNZ7J8i5hzEZN-1

**Comment by aktdenis** [comment]
@mnlytic thanks! much appreciated. 
added your ideas in the issue above. @zachhorn had a look at the content and might find it useful. 

regarding the "get started" CTA. 
there are so many ways to get started (and even more are in the making) that's why we thought presenting those options on a separate page. more info is in this issue: https://github.com/akash-network/website/issues/215
