### ISSUE TITLE
Too many "You" in the paragraph

### ISSUE THREAD

**Issue by AKTPete** [akash-network/website-5-archive#35]
"You will own your cloud, and you will be happy
With Akash, you have the power to own your cloud. You can deploy your own cloud infrastructure, and you can sell your unused cloud resources to others. You can also buy cloud resources from others, and you can use them to run your applications."

Suggestions: 

"Own your cloud, own your Independence"
With Akash, you have the power to own your cloud. Deploy your cloud infrastructure, sell your unused cloud resources, and/or buy cloud resources from others to run your applications

**Comment by gosuri** [comment]
How about this?

Deploy your cloud infrastructure, sell unused cloud resources to others and buy cloud resources from others, and you can use them to run your applications

**Comment by zachhorn** [comment]
I like both options. Another suggestion:

> Discover the full potential of cloud computing with Akash. Deploy your own cloud infrastructure and optimize it by selling unused capacity to the network. Access this distributed network of cloud resources to run applications on demand.

**Comment by zachhorn** [comment]
#55 Updated the copy above.

**Comment by AKTPete** [comment]
Whatever the solution, the title line must change. 

"You will be happy" doesn't sit well. 

It will be memed.
