### ISSUE TITLE
Add link to merch store

### ISSUE THREAD

**Issue by corysturtevant** [akash-network/website-5-archive#36]
## Summary

Link to merch store shop.akash.network appears to be missing.

### Basic example

https://shop.akash.network/

### Motivation

So the community can find the shop

**Comment by gosuri** [comment]
Which section do you propose we the link under? I think Community is ideal.

I think its a good time to have a footer with expanded menu options.

**Comment by corysturtevant** [comment]
It's lived under community previously, that makes sense
