### ISSUE TITLE
Missing an "is"

### ISSUE THREAD

**Issue by AKTPete** [akash-network/website-5-archive#37]
In the paragraph below

"Infrastructure as Code
Akash's orchestration layer lets you use a language called SDL, which is written in YAML and  **is**  easy to understand. Using this, you can create complex deployments that span multiple areas and providers. You can choose the resources you want to use and decide on your price too."

**Comment by gosuri** [comment]
How about this?

Akash's orchestration layer is powered by SDL. This simple-to-use YAML-based language lets you create complex deployments that span multiple areas and providers while choosing the resources you want to use and deciding on your price.
