### ISSUE TITLE
site needs to have a press section

### ISSUE THREAD

**Issue by gosuri** [akash-network/website-5-archive#52]
## Summary

Akash gets quite a lot a press, but that information is not cataloged or archived properly. Including a press section (possibly under community) is beneficial

Press section to include:

- Press Releases
- Press Articles archived by Date
- Media Kit

Checkout old [site](https://stage.akash.network/press) for reference

**Comment by brewsterdrinkwater** [comment]
Zach and denis brought this up at sig-design.

**Comment by HoomanHQ** [comment]
is this issue still open?  can we please have access to old site for more details?

**Comment by aktdenis** [comment]
@HoomanHQ design is in the making, it was discussed in our last sig-design meeting. we need couple of tweaks on the content and will be ready next week

**Comment by aktdenis** [comment]
@zachhorn any ideas what could we include in press kit? 

<img width="1328" alt="Screenshot 2023-07-26 at 15 27 33" src="https://github.com/akash-network/website/assets/116030971/86ba3612-42ea-4fa9-a1bf-70395bf322bc">

cc @brewsterdrinkwater
