### ISSUE TITLE
Privacy Link results in 404 error

### ISSUE THREAD

**Issue by lechenghiskhan** [akash-network/website-5-archive#64]
## Description

The privacy link at the bottom right-hand side of the site's main page leads to a page not found error.

### Steps to reproduce

Just click the privacy link and results in below:
<img width="955" alt="image" src="https://user-images.githubusercontent.com/68354230/212144291-0e5cb83b-240d-49fe-8d75-77854c65a4a0.png">

**Comment by gosuri** [comment]
Yes. This is noted in #32.
