### ISSUE TITLE
Articles in need of updating - what to do?

### ISSUE THREAD

**Issue by figurestudios** [akash-network/website-5-archive#69]
[This article](https://github.com/akash-network/website/blob/main/content/en/blog/akash-network-provides-decentralized-cloud-to-the-largest-internet-of-things-iot-network-helium/index.md) is an example of an article that was written before the `provider-services` command was introduced and other information changing over time. Do we update old articles to keep information relevant, or should users simply understand that old articles are not maintained? This includes testing old SDLs, fact-checking information, and possibly removing or adding disclaimers that are no longer the case.

**Comment by gosuri** [comment]
Let's try and keep all articles as up-to-date as possible. Also, there are discussions about a new CLI for Akash in [sig-clients](https://github.com/akash-network/community/tree/main/sig-clients) and its probably worth waiting for that before updating docs.

**Comment by figurestudios** [comment]
Understood, thanks!
