### ISSUE TITLE
migrate ecosystem to website

### ISSUE THREAD

**Issue by gosuri** [akash-network/website-5-archive#76]
The [ecosystem.akash.network](https://ecosystem.akash.network) is maintained separately under [ovrclk/akash-ecosystem](https://github.com/ovrclk/akash-ecosystem).

Merge this project into the website makes it easier to maintain and better for SEO.

**Comment by HoomanHQ** [comment]
@brewsterdrinkwater is this issue still open?? Or already being addressed internally??

**Comment by aktdenis** [comment]
@HoomanHQ thanks for the detailed plan. Issue is still available. 
Design is ready, link should be pinned in the Discord - wg-akash-website.

Providing a preview below:
- We let users decide between tools (built on and for Akash) and Projects deployed on Akash
<img width="907" alt="Screenshot 2023-08-10 at 14 53 06" src="https://github.com/akash-network/website/assets/116030971/03f7b3f8-e4e3-4d5a-92f4-ac7e7612429e">

Overview of the projects and tools:
<img width="956" alt="Screenshot 2023-08-10 at 14 54 05" src="https://github.com/akash-network/website/assets/116030971/df34b580-e367-4571-a696-f3e6a33a577f">
<img width="968" alt="Screenshot 2023-08-10 at 14 54 13" src="https://github.com/akash-network/website/assets/116030971/971ddb45-4701-43f3-b17e-c9c594073e52">
