### ISSUE TITLE
Update 'Subscribe to newsletter' link on the home page

### ISSUE THREAD

**Issue by zachhorn** [akash-network/website-5-archive#89]
Currently points to Revue (which was just shut down by Twitter). I'll create a signup typeform by EOD today and open PR with the updated link.

<img width="1895" alt="image" src="https://user-images.githubusercontent.com/24351900/213241157-f33a24b8-8b37-4901-bcc7-f6187cfc992d.png">

**Comment by zachhorn** [comment]
Update PR opened: #90

**Comment by gosuri** [comment]
Fixed with #90
